<?php

return array(
    0 => array('name' => 'Deutschland'),
    1 => array('name' => 'Afghanistan'),
    2 => array('name' => 'Ägypten'),
    3 => array('name' => 'Albanien'),
    4 => array('name' => 'Algerien'),
    5 => array('name' => 'Andorra'),
    6 => array('name' => 'Angola'),
    7 => array('name' => 'Antigua und Barbuda'),
    8 => array('name' => 'Äquatorialguinea'),
    9 => array('name' => 'Argentinien'),
    10 => array('name' => 'Armenien'),
    11 => array('name' => 'Aserbaidschan'),
    12 => array('name' => 'Äthiopien'),
    13 => array('name' => 'Australien'),
    14 => array('name' => 'Bahamas'),
    15 => array('name' => 'Bahrain'),
    16 => array('name' => 'Bangladesch'),
    17 => array('name' => 'Barbados'),
    18 => array('name' => 'Belarus'),
    19 => array('name' => 'Belgien'),
    20 => array('name' => 'Belize'),
    21 => array('name' => 'Benin'),
    22 => array('name' => 'Bhutan'),
    23 => array('name' => 'Bolivien'),
    24 => array('name' => 'Bosnien und Herzegowina'),
    25 => array('name' => 'Botsuana'),
    26 => array('name' => 'Brasilien'),
    27 => array('name' => 'Brunei Darussalam'),
    28 => array('name' => 'Bulgarien'),
    29 => array('name' => 'Burkina Faso'),
    30 => array('name' => 'Burundi'),
    31 => array('name' => 'Cabo Verde'),
    32 => array('name' => 'Chile'),
    33 => array('name' => 'China'),
    34 => array('name' => 'Cookinseln'),
    35 => array('name' => 'Costa Rica'),
    36 => array('name' => 'Côte d\'Ivoire'),
    37 => array('name' => 'Dänemark'),
    38 => array('name' => 'Dominica'),
    39 => array('name' => 'Dominikanische Republik'),
    40 => array('name' => 'Dschibuti'),
    41 => array('name' => 'Ecuador'),
    42 => array('name' => 'El Salvador'),
    43 => array('name' => 'Eritrea'),
    44 => array('name' => 'Estland'),
    45 => array('name' => 'Eswatini'),
    46 => array('name' => 'Fidschi'),
    47 => array('name' => 'Finnland'),
    48 => array('name' => 'Frankreich'),
    49 => array('name' => 'Gabun'),
    50 => array('name' => 'Gambia'),
    51 => array('name' => 'Georgien'),
    52 => array('name' => 'Ghana'),
    53 => array('name' => 'Grenada'),
    54 => array('name' => 'Griechenland'),
    55 => array('name' => 'Großbritannien'),
    56 => array('name' => 'Guatemala'),
    57 => array('name' => 'Guinea'),
    58 => array('name' => 'Guinea-Bissau'),
    59 => array('name' => 'Guyana'),
    60 => array('name' => 'Haiti'),
    61 => array('name' => 'Honduras'),
    62 => array('name' => 'Indien'),
    63 => array('name' => 'Indonesien'),
    64 => array('name' => 'Irak'),
    65 => array('name' => 'Iran'),
    66 => array('name' => 'Irland'),
    67 => array('name' => 'Island'),
    68 => array('name' => 'Israel'),
    69 => array('name' => 'Italien'),
    70 => array('name' => 'Jamaika'),
    71 => array('name' => 'Japan'),
    72 => array('name' => 'Jemen'),
    73 => array('name' => 'Jordanien'),
    74 => array('name' => 'Kambodscha'),
    75 => array('name' => 'Kamerun'),
    76 => array('name' => 'Kanada'),
    77 => array('name' => 'Kasachstan'),
    78 => array('name' => 'Katar'),
    79 => array('name' => 'Kenia'),
    80 => array('name' => 'Kirgisistan'),
    81 => array('name' => 'Kiribati'),
    82 => array('name' => 'Kolumbien'),
    83 => array('name' => 'Komoren'),
    84 => array('name' => 'Kongo'),
    85 => array('name' => 'Kongo, Demokratische Republik'),
    86 => array('name' => 'Korea, Demokratische Volksrepublik'),
    87 => array('name' => 'Korea, Republik'),
    88 => array('name' => 'Kosovo'),
    89 => array('name' => 'Kroatien'),
    90 => array('name' => 'Kuba'),
    91 => array('name' => 'Kuwait'),
    92 => array('name' => 'Laos'),
    93 => array('name' => 'Lesotho'),
    94 => array('name' => 'Lettland'),
    95 => array('name' => 'Libanon'),
    96 => array('name' => 'Liberia'),
    97 => array('name' => 'Libyen'),
    98 => array('name' => 'Liechtenstein'),
    99 => array('name' => 'Litauen'),
    100 => array('name' => 'Luxemburg'),
    101 => array('name' => 'Madagaskar'),
    102 => array('name' => 'Malawi'),
    103 => array('name' => 'Malaysia'),
    104 => array('name' => 'Malediven'),
    105 => array('name' => 'Mali'),
    106 => array('name' => 'Malta'),
    107 => array('name' => 'Marokko'),
    108 => array('name' => 'Marshallinseln'),
    109 => array('name' => 'Mauretanien'),
    110 => array('name' => 'Mauritius'),
    111 => array('name' => 'Mexiko'),
    112 => array('name' => 'Mikronesien'),
    113 => array('name' => 'Moldau'),
    114 => array('name' => 'Monaco'),
    115 => array('name' => 'Mongolei'),
    116 => array('name' => 'Montenegro'),
    117 => array('name' => 'Mosambik'),
    118 => array('name' => 'Myanmar'),
    119 => array('name' => 'Namibia'),
    120 => array('name' => 'Nauru'),
    121 => array('name' => 'Nepal'),
    122 => array('name' => 'Neuseeland'),
    123 => array('name' => 'Nicaragua'),
    124 => array('name' => 'Niederlande'),
    125 => array('name' => 'Niger'),
    126 => array('name' => 'Nigeria'),
    127 => array('name' => 'Nordmazedonien'),
    128 => array('name' => 'Norwegen'),
    129 => array('name' => 'Oman'),
    130 => array('name' => 'Österreich'),
    131 => array('name' => 'Pakistan'),
    132 => array('name' => 'Palau'),
    133 => array('name' => 'Panama'),
    134 => array('name' => 'Papua-Neuguinea'),
    135 => array('name' => 'Paraguay'),
    136 => array('name' => 'Peru'),
    137 => array('name' => 'Philippinen'),
    138 => array('name' => 'Polen'),
    139 => array('name' => 'Portugal'),
    140 => array('name' => 'Ruanda'),
    141 => array('name' => 'Rumänien'),
    142 => array('name' => 'Russische Föderation'),
    143 => array('name' => 'Salomonen'),
    144 => array('name' => 'Sambia'),
    145 => array('name' => 'Samoa'),
    146 => array('name' => 'San Marino'),
    147 => array('name' => 'São Tomé und Príncipe'),
    148 => array('name' => 'Saudi-Arabien'),
    149 => array('name' => 'Schweden'),
    150 => array('name' => 'Schweiz'),
    151 => array('name' => 'Senegal'),
    152 => array('name' => 'Serbien'),
    153 => array('name' => 'Seychellen'),
    154 => array('name' => 'Sierra Leone'),
    155 => array('name' => 'Simbabwe'),
    156 => array('name' => 'Singapur'),
    157 => array('name' => 'Slowakei'),
    158 => array('name' => 'Slowenien'),
    159 => array('name' => 'Somalia'),
    160 => array('name' => 'Spanien'),
    161 => array('name' => 'Sri Lanka'),
    162 => array('name' => 'St. Kitts und Nevis'),
    163 => array('name' => 'St. Lucia'),
    164 => array('name' => 'St. Vincent und die Grenadinen'),
    165 => array('name' => 'Südafrika'),
    166 => array('name' => 'Sudan'),
    167 => array('name' => 'Südsudan'),
    168 => array('name' => 'Suriname'),
    169 => array('name' => 'Syrien'),
    170 => array('name' => 'Tadschikistan'),
    171 => array('name' => 'Taiwan'),
    172 => array('name' => 'Tansania'),
    173 => array('name' => 'Thailand'),
    174 => array('name' => 'Timor-Leste'),
    175 => array('name' => 'Togo'),
    176 => array('name' => 'Tonga'),
    177 => array('name' => 'Trinidad und Tobago'),
    178 => array('name' => 'Tschad'),
    179 => array('name' => 'Tschechische Republik'),
    180 => array('name' => 'Tunesien'),
    181 => array('name' => 'Türkei'),
    182 => array('name' => 'Turkmenistan'),
    183 => array('name' => 'Tuvalu'),
    184 => array('name' => 'Uganda'),
    185 => array('name' => 'Ukraine'),
    186 => array('name' => 'Ungarn'),
    187 => array('name' => 'Uruguay'),
    188 => array('name' => 'Usbekistan'),
    189 => array('name' => 'Vanuatu'),
    190 => array('name' => 'Vatikanstadt'),
    191 => array('name' => 'Venezuela'),
    192 => array('name' => 'Vereinigte Arabische Emirate'),
    193 => array('name' => 'Vereinigte Staaten'),
    194 => array('name' => 'Vietnam'),
    195 => array('name' => 'Zentralafrikanische Republik'),
    196 => array('name' => 'Zypern'),
);